#!/usr/bin/env node
// Regenerate STATUS.md — a central status board for every public repository.
//
// Columns are live shields.io badges (CI/check status, commit freshness, open
// issues, top language), so the board stays current on every page load. Only the
// repository *list* needs regenerating when repos are added or removed — that is
// what this script does, from the authenticated GitHub API.
//
//   node scripts/build-status.mjs
//
// Run locally with `gh` authenticated, or in CI where GH_TOKEN is provided.

import { execSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const OWNER = "asmuelle";
const STYLE = "flat-square";
const PAGES_BASE = "https://asmuelle.github.io";
const TODAY = new Date().toISOString().slice(0, 10);

// --paginate + --jq streams one compact JSON object per line (NDJSON).
const raw = execSync(
  `gh api --paginate "users/${OWNER}/repos?per_page=100&type=owner" ` +
    `--jq '.[] | select(.fork==false and .archived==false and .private==false) ` +
    `| {name, has_pages, branch: .default_branch, lang: (.language // "")}'`,
  { encoding: "utf8", maxBuffer: 16 * 1024 * 1024 }
);

const repos = raw
  .trim()
  .split("\n")
  .filter(Boolean)
  .map((l) => JSON.parse(l))
  .filter((r) => r.name !== "asmuelle.github.io") // the host repo renders this board; don't list itself
  .sort((a, b) => a.name.localeCompare(b.name));

const img = (alt, path, q = "") => `![${alt}](https://img.shields.io/github/${path}?style=${STYLE}${q})`;
const ci = (r) => img("CI", `check-runs/${OWNER}/${r.name}/${r.branch}`, "&label=CI");
const commit = (r) => img("last commit", `last-commit/${OWNER}/${r.name}`);
const issues = (r) => img("issues", `issues/${OWNER}/${r.name}`);
const language = (r) => (r.lang ? img("language", `languages/top/${OWNER}/${r.name}`) : "—");
const repoLink = (r) => `[${r.name}](https://github.com/${OWNER}/${r.name})`;

const pages = repos.filter((r) => r.has_pages);
const libs = repos.filter((r) => !r.has_pages);

const pagesTable = [
  "| Repository | CI | Last commit | Issues | Live |",
  "|---|---|---|---|---|",
  ...pages.map((r) => `| ${repoLink(r)} | ${ci(r)} | ${commit(r)} | ${issues(r)} | [site ↗](${PAGES_BASE}/${r.name}/) |`),
].join("\n");

const libsTable = [
  "| Repository | CI | Last commit | Issues | Language |",
  "|---|---|---|---|---|",
  ...libs.map((r) => `| ${repoLink(r)} | ${ci(r)} | ${commit(r)} | ${issues(r)} | ${language(r)} |`),
].join("\n");

const md = `# Repository status

Live CI/check status, commit freshness, and open-issue counts across every public
repository. Badges refresh automatically; the list is regenerated daily by
[\`refresh-repos.yml\`](.github/workflows/refresh-repos.yml).

_Last generated ${TODAY} · ${repos.length} repositories — ${pages.length} Pages sites, ${libs.length} libraries & tools._

## 🌐 GitHub Pages sites

${pagesTable}

## 📦 Libraries & tools

${libsTable}

---

<sub>The **CI** badge reflects the combined check-run status of the latest commit
on each repo's default branch. Generated by \`scripts/build-status.mjs\` — do not
edit \`STATUS.md\` by hand.</sub>
`;

writeFileSync(resolve(ROOT, "STATUS.md"), md);
console.log(`STATUS.md: ${repos.length} repos (${pages.length} pages, ${libs.length} libs)`);
